<?php
/**
 * Copyright © Magefan (support@magefan.com). All rights reserved.
 * Please visit Magefan.com for license details (https://magefan.com/end-user-license-agreement).
 *
 * Glory to Ukraine! Glory to the heroes!
 */
?>
<?php
/**
 * Blog tag claud sidebar template
 *
 * @var $block \Magefan\Blog\Block\Sidebar\TagClaud
 */
?>
<?php $tags = $block->getTags(); ?>

<?php if (count($tags)) { ?>
    <div class="widget block blog-tags" data-bind="scope: 'tagclaud'">
        <div class="block-title">
            <strong><?= $block->escapeHtml(__('Tags')) ?></strong>
        </div>

        <div class="block-content">
            <ul>
                <?php foreach ($tags as $tag) { ?>
                    <li><?php $title = $tag->getTitle() ?>
                        <a href="<?= $block->escapeUrl($tag->getTagUrl()) ?>" title="<?= $block->escapeHtml($title) ?>">
                            <?= $block->escapeHtml($title) ?>
                        </a>
                    </li>
                <?php } ?>
            </ul>
        </div>
    </div>
<?php } ?>
