<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<?php
/** @var $block \Magento\Framework\View\Element\Template */
/** @var $escaper \Magento\Framework\Escaper */
/** @var $configProvider \Magento\Search\ViewModel\ConfigProvider */
$configProvider = $block->getData('configProvider');
/** @var $helper \Magento\Search\Helper\Data */
$helper            = $configProvider->getSearchHelperData();
$allowedSuggestion = $configProvider->isSuggestionsAllowed();
$quickSearchUrl    = $allowedSuggestion ? $escaper->escapeUrl($helper->getSuggestUrl()) : '';
$_config           = $this->helper('BzoTech\AjaxSearch\Helper\Data');
?>
<div class="block block-search ajax-search">
    <div class="block block-title"><strong><?= $escaper->escapeHtml(__('Search')) ?></strong></div>
    <div class="block block-content">
        <form class="form minisearch" id="search_mini_form"
              action="<?= $escaper->escapeUrl($helper->getResultUrl()) ?>" method="get">
            <div class="field search">
                <label class="label" for="search" data-role="minisearch-label">
                    <span><?= $escaper->escapeHtml(__('Search')) ?></span>
                </label>
                <div class="control">
                    <input id="search"
                           type="text"
                           name="<?= $escaper->escapeHtmlAttr($helper->getQueryParamName()) ?>"
                           value="<?= /* @noEscape */
                           $helper->getEscapedQueryText() ?>"
                           placeholder="<?= $escaper->escapeHtmlAttr(__('Search entire store here...')) ?>"
                           class="input-text"
                           maxlength="<?= $escaper->escapeHtmlAttr($helper->getMaxQueryLength()) ?>"
                           role="combobox"
                           aria-haspopup="false"
                           aria-autocomplete="both"
                           autocomplete="off"
                           aria-expanded="false"/>
                    <div id="bzotech_search_autocomplete" class="bzotech-search-autocomplete">
                        <a class="close-search-ajax"
                           href="javascript:void(0);"><span><?php echo __('Close') ?></span></a>

                        <div class="drop-search-content"></div>

                        <div class="loading-search">
                            <div class="loader-ajax-search"></div>
                        </div>
                    </div>

                </div>
            </div>
            <div class="actions">
                <button type="submit"
                        title="<?= $escaper->escapeHtml(__('Search')) ?>"
                        class="action search"
                        aria-label="Search"
                >
                    <span><?= $escaper->escapeHtml(__('Search')) ?></span>
                </button>
            </div>
        </form>
    </div>
</div>
