<?php

use Magento\Framework\App\Action\Action;

$productCollection = $block->getProducts();
$_helper           = $this->helper('Magento\Catalog\Helper\Output');
$imageDisplayArea  = 'category_page_grid';
$pos               = $block->getPositioned();
$templateType      = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
$viewMode          = 'grid';
$blockPrefix       = 'bzotech-widget-' . rand();
?>

<?php if (!$productCollection->count()): ?>
    <div class="message info empty">
        <div><?= $escaper->escapeHtml(__('We can\'t find products matching the selection.')) ?></div>
    </div>
<?php else: ?>
    <div id="<?php echo $blockPrefix ?>"
         class="block widget-grid-product-custom bzotech-widget-products bzotech-grid-product">
        <div class="block-title">
            <strong><?php echo $block->escapeHtml($block->getData('widget_grid_title')) ?></strong>
        </div>

        <div class="block-content">
            <?php
            if ($block->getData('product_source') == 'countdown_products') {
                $dateTo = $block->getData('date_to');
                ?>
                <div class="group-countdown">
                    <div class="countdown-item"
                         data-timer="<?php echo date("Y/m/d H:i:s", strtotime($dateTo)); ?>">
                        <div class="deals-time time-day">
                            <div class="num-time"></div>
                            <div class="title-time"></div>
                        </div>
                        <div class="deals-time time-hours">
                            <div class="num-time"></div>
                            <div class="title-time"></div>
                        </div>
                        <div class="deals-time time-mins">
                            <div class="num-time"></div>
                            <div class="title-time"></div>
                        </div>
                        <div class="deals-time time-secs">
                            <div class="num-time"></div>
                            <div class="title-time"></div>
                        </div>
                    </div>
                </div>
            <?php } ?>

            <div class="products wrapper <?php /* @escapeNotVerified */
            echo $viewMode; ?> products-<?php /* @escapeNotVerified */
            echo $viewMode; ?>">
                <div class="products list items product-items">
                    <?php foreach ($productCollection as $_product): ?>
                        <div class="item product product-item">
                            <div class="product-item-info">
                                <?php
                                $productImage = $block->getImage($_product, $imageDisplayArea);
                                if ($pos != null) {
                                    $position = 'left:' . $productImage->getWidth() . 'px;'
                                        . 'top:' . $productImage->getHeight() . 'px;';
                                }
                                ?>
                                <a href="<?php /* @escapeNotVerified */
                                echo $_product->getProductUrl() ?>" class="product photo product-item-photo"
                                   tabindex="-1">
                                    <?php echo $productImage->toHtml(); ?>
                                </a>

                                <div class="product details product-item-details">
                                    <?php
                                    if ((int)$block->getData('countdown_timer') && !empty($_product->getSpecialPrice()) && !empty($_product->getSpecialToDate())) {
                                        $specialToDate = $_product->getSpecialToDate();
                                        ?>
                                        <div class="countdown-item"
                                             data-timer="<?php echo date("Y/m/d H:i:s", strtotime($specialToDate)); ?>">
                                            <div class="deals-time time-day">
                                                <div class="num-time"></div>
                                                <div class="title-time"></div>
                                            </div>
                                            <div class="deals-time time-hours">
                                                <div class="num-time"></div>
                                                <div class="title-time"></div>
                                            </div>
                                            <div class="deals-time time-mins">
                                                <div class="num-time"></div>
                                                <div class="title-time"></div>
                                            </div>
                                            <div class="deals-time time-secs">
                                                <div class="num-time"></div>
                                                <div class="title-time"></div>
                                            </div>
                                        </div>
                                    <?php } ?>

                                    <?php
                                    $_productNameStripped = $block->stripTags($_product->getName(), null, true);
                                    ?>
                                    <strong class="product name product-item-name">
                                        <a class="product-item-link"
                                           href="<?php /* @escapeNotVerified */
                                           echo $_product->getProductUrl() ?>">
                                            <?php /* @escapeNotVerified */
                                            echo $_helper->productAttribute($_product, $_product->getName(), 'name'); ?>
                                        </a>
                                    </strong>

                                    <?php echo $block->getReviewsSummaryHtml($_product, $templateType); ?>

                                    <?php echo $block->getProductPrice($_product) ?>

                                    <?php echo $block->getProductDetailsHtml($_product); ?>

                                    <div class="product-item-inner">
                                        <div class="product actions product-item-actions"<?= strpos($pos, $viewMode . '-actions') ? $position : '' ?>>
                                            <div class="actions-primary"<?= strpos($pos, $viewMode . '-primary') ? $position : '' ?>>
                                                <?php if ($_product->isSaleable()): ?>
                                                    <?php $postParams = $block->getAddToCartPostParams($_product); ?>
                                                    <form data-role="tocart-form"
                                                          data-product-sku="<?= $block->escapeHtml($_product->getSku()) ?>"
                                                          action="<?= /* @NoEscape */
                                                          $postParams['action'] ?>" method="post">
                                                        <input type="hidden" name="product"
                                                               value="<?= /* @escapeNotVerified */
                                                               $postParams['data']['product'] ?>">
                                                        <input type="hidden" name="<?= /* @escapeNotVerified */
                                                        Action::PARAM_NAME_URL_ENCODED ?>"
                                                               value="<?= /* @escapeNotVerified */
                                                               $postParams['data'][Action::PARAM_NAME_URL_ENCODED] ?>">
                                                        <?= $block->getBlockHtml('formkey') ?>
                                                        <button type="submit"
                                                                title="<?= $block->escapeHtml(__('Add to Cart')) ?>"
                                                                class="action tocart primary">
                                                    <span><?= /* @escapeNotVerified */
                                                        __('Add to Cart') ?></span>
                                                        </button>
                                                    </form>
                                                <?php else: ?>
                                                    <?php if ($_product->isAvailable()): ?>
                                                        <div class="stock available"><span><?= /* @escapeNotVerified */
                                                                __('In stock') ?></span></div>
                                                    <?php else: ?>
                                                        <div class="stock unavailable"><span><?= /* @escapeNotVerified */
                                                                __('Out of stock') ?></span></div>
                                                    <?php endif; ?>
                                                <?php endif; ?>
                                            </div>
                                            <div data-role="add-to-links"
                                                 class="actions-secondary"<?= strpos($pos, $viewMode . '-secondary') ? $position : '' ?>>
                                                <?php if ($this->helper('Magento\Wishlist\Helper\Data')->isAllow()): ?>
                                                    <a href="#"
                                                       data-post='<?php /* @escapeNotVerified */
                                                       echo $block->getAddToWishlistParams($_product); ?>'
                                                       class="action towishlist" data-action="add-to-wishlist"
                                                       title="<?php /* @escapeNotVerified */
                                                       echo __('Add to Wish List') ?>">
                                                            <span><?php /* @escapeNotVerified */
                                                                echo __('Add to Wish List') ?></span>
                                                    </a>
                                                <?php endif; ?>
                                                <?php if ($block->getAddToCompareUrl()): ?>
                                                    <?php $compareHelper = $this->helper('Magento\Catalog\Helper\Product\Compare'); ?>
                                                    <a href="#" class="action tocompare"
                                                       data-post='<?php /* @escapeNotVerified */
                                                       echo $compareHelper->getPostDataParams($_product); ?>'
                                                       title="<?php /* @escapeNotVerified */
                                                       echo __('Add to Compare') ?>">
                                                            <span><?php /* @escapeNotVerified */
                                                                echo __('Add to Compare') ?></span>
                                                    </a>
                                                <?php endif; ?>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    <?php endforeach; ?>
                </div>
            </div>
        </div>
    </div>

    <script type="text/javascript">
        require([
            'jquery'
        ], function ($) {
            ;(function (el) {
                var $element = $(el);

                function _countDown(date, id) {
                    var dateNow = new Date();
                    var amount = date.getTime() - dateNow.getTime();
                    delete dateNow;
                    if (amount < 0) {
                        id.html("Now!");
                    } else {
                        var days = 0;
                        hours = 0;
                        mins = 0;
                        secs = 0;
                        out = "";
                        amount = Math.floor(amount / 1000);
                        days = Math.floor(amount / 86400);
                        amount = amount % 86400;
                        hours = Math.floor(amount / 3600);
                        amount = amount % 3600;
                        mins = Math.floor(amount / 60);
                        amount = amount % 60;
                        secs = Math.floor(amount);
                        $(".time-day .num-time", id).text(days);
                        $(".time-day .title-time", id).text(((days <= 1) ? "<?php echo __('Day') ?>" : "<?php echo __('Days') ?>"));
                        $(".time-hours .num-time", id).text(hours);
                        $(".time-hours .title-time", id).text(((hours <= 1) ? "<?php echo __('Hour') ?>" : "<?php echo __('Hours') ?>"));
                        $(".time-mins .num-time", id).text(mins);
                        $(".time-mins .title-time", id).text(((mins <= 1) ? "<?php echo __('Min') ?>" : "<?php echo __('Mins') ?>"));
                        $(".time-secs .num-time", id).text(secs);
                        $(".time-secs .title-time", id).text(((secs <= 1) ? "<?php echo __('Sec') ?>" : "<?php echo __('Secs') ?>"));
                        setTimeout(function () {
                            _countDown(date, id)
                        }, 1000);
                    }
                }

                $(".countdown-item", $element).each(function () {
                    var timer = $(this).data('timer');
                    var data = new Date(timer);
                    _countDown(data, $(this));
                });
            })('#<?php echo $blockPrefix ?>');
        });
    </script>
<?php endif; ?>