<?php
/**
 * @category BZOTech
 * @package BzoTech_PopupLogin
 * @version 1.0.0
 * @copyright Copyright (c) 2022 BZOTech Company. All Rights Reserved.
 * @license - Copyrighted Commercial Software
 * @author BZOTech Company <contact@bzotech.com>
 * @link https://bzotech.com
 */

/** @var \Magento\Customer\Block\Account\Forgotpassword $block */
$_config        = $this->helper('BzoTech\PopupLogin\Helper\Data');
$currentPageUrl = $_config->getUrlPage();
?>
<form class="form password forget"
      action="<?= $block->escapeUrl($block->getUrl('customer/account/forgotpasswordpost')) ?>"
      method="post"
      id="form-validate-forgot"
      data-mage-init='{"validation":{}}'>
    <fieldset class="fieldset" data-hasrequired="<?= $block->escapeHtmlAttr(__('* Required Fields')) ?>">
        <div class="field note"><?= $block->escapeHtml(__('Please enter your email address below to receive a password reset link.')) ?></div>
        <div class="field email required">
            <label for="email_address" class="label"><span><?= $block->escapeHtml(__('Email')) ?></span></label>
            <div class="control">
                <input type="email" name="email" alt="email" id="email_address_forgot" class="input-text"
                       value="<?= $block->escapeHtmlAttr($block->getEmailValue()) ?>"
                       data-mage-init='{"mage/trim-input":{}}' data-validate="{required:true, 'validate-email':true}">
            </div>
        </div>
        <?= $block->getChildHtml('bzotech_form_additional_info_forgot') ?>
        <?= $block->getChildHtml('captcha.forgot') ?>
        <?= $block->getChildHtml('recaptcha.forgot.popup') ?>
    </fieldset>
    <div class="actions-toolbar">
        <div class="primary">
            <button type="submit" class="action submit primary">
                <span><?= $block->escapeHtml(__('Reset My Password')) ?></span></button>
        </div>
    </div>

    <?php if (!str_contains($currentPageUrl, 'customer/account/login')) { ?>
        <div class="back-to-login">
            <a class="back-login trigger-login" href="javascript:void(0)">
                <span><?php echo $block->escapeHtml(__('Go to Login')) ?></span>
            </a>
        </div>
    <?php } ?>
</form>
<script type="text/x-magento-init">
    {
        "*": {
            "Magento_Customer/js/block-submit-on-send": {
                "formId": "form-validate-forgot"
            }
        }
    }


</script>
