<?php
/**
 * @category BZOTech
 * @package BzoTech_PopupLogin
 * @version 1.0.0
 * @copyright Copyright (c) 2022 BZOTech Company. All Rights Reserved.
 * @license - Copyrighted Commercial Software
 * @author BZOTech Company <contact@bzotech.com>
 * @link https://bzotech.com
 */

/** @var \Magento\Customer\Block\Form\Login $block */

$_config        = $this->helper('BzoTech\PopupLogin\Helper\Data');
$currentPageUrl = $_config->getUrlPage();
?>
<div class="block block-customer-login">
    <div class="block-content" aria-labelledby="block-customer-login-heading">
        <form class="form form-login"
              action="<?= $block->escapeUrl($block->getPostActionUrl()) ?>"
              method="post"
              id="login-form-popup"
              data-mage-init='{"validation":{}}'>
            <?= $block->getBlockHtml('formkey') ?>
            <fieldset class="fieldset login" data-hasrequired="<?= $block->escapeHtml(__('* Required Fields')) ?>">
                <input type="hidden" id="popup-redirect" name="login[redirect]"
                       value="<?php echo $_config->getRedirectUrl(); ?>">

                <div class="field email required">
                    <label class="label" for="email"><span><?= $block->escapeHtml(__('Email')) ?></span></label>
                    <div class="control">
                        <input name="login[username]" value="<?= $block->escapeHtmlAttr($block->getUsername()) ?>"
                            <?php if ($block->isAutocompleteDisabled()): ?> autocomplete="off"<?php endif; ?>
                               id="email_login" type="email" class="input-text"
                               title="<?= $block->escapeHtmlAttr(__('Email')) ?>"
                               data-mage-init='{"mage/trim-input":{}}'
                               data-validate="{required:true, 'validate-email':true}">
                    </div>
                </div>
                <div class="field password required">
                    <label for="pass" class="label"><span><?= $block->escapeHtml(__('Password')) ?></span></label>
                    <div class="control">
                        <input name="login[password]" type="password"
                            <?php if ($block->isAutocompleteDisabled()): ?> autocomplete="off"<?php endif; ?>
                               class="input-text" id="pass_login"
                               title="<?= $block->escapeHtmlAttr(__('Password')) ?>"
                               data-validate="{required:true}">
                    </div>
                </div>

                <?= $block->getChildHtml('bzotech_form_additional_info_login') ?>
                <?= $block->getChildHtml('captcha.login.popup') ?>
                <?= $block->getChildHtml('recaptcha.login') ?>
                <div class="actions-toolbar">
                    <div class="primary">
                        <button type="submit" class="action login primary" name="send" id="send2_login">
                            <span><?= $block->escapeHtml(__('Sign In')) ?></span></button>
                    </div>
                    <?php if (!str_contains($currentPageUrl, 'customer/account/forgotpassword')) { ?>
                        <div class="secondary">
                            <a class="action remind" href="<?= $block->escapeUrl($block->getForgotPasswordUrl()) ?>">
                                <span><?= $block->escapeHtml(__('Forgot Your Password?')) ?></span>
                            </a>
                        </div>
                    <?php } ?>
                </div>
            </fieldset>
        </form>

        <?php if (!str_contains($currentPageUrl, 'customer/account/create')) { ?>
            <div class="bottom-popup">
                <div class="sub-title"><?php echo $block->escapeHtml(__('Don\'t have an account?')) ?></div>
                <div class="trigger-button">
                    <a class="trigger-create" href="javascript:void(0)">
                        <span><?php echo $block->escapeHtml(__('Sign Up Now')) ?></span>
                    </a>
                </div>
            </div>
        <?php } ?>
    </div>
    <script type="text/x-magento-init">
        {
            "*": {
                "Magento_Customer/js/block-submit-on-send": {
                    "formId": "login-form-popup"
                }
            }
        }
    </script>
</div>
