<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/**
 * @var \Magento\Theme\Block\Html\Header $block
 */

$_config     = $this->helper('BzoTech\Petshop\Helper\Data');
$_configCore = $this->helper('BzoTech\ThemeCore\Helper\Data');
$footerStyle = $_config->getThemeConfig('theme_layout/layout_footer/footer_style');

include($block->getTemplateFile("BzoTech_Petshop::html/footer/" . $footerStyle . ".phtml"));

?>
