<?php
/**
 * @category BZOTech
 * @package BzoTech_AjaxCart
 * @version 1.0.0
 * @copyright Copyright (c) 2022 BZOTech Company. All Rights Reserved.
 * @license - Copyrighted Commercial Software
 * @author BZOTech Company <contact@bzotech.com>
 * @link https://bzotech.com
 */

if (!(int)$this->_getConfig('isenabled', 1))
    return;

$countdown_number = (int)$this->_getConfig('countdown_number') > 0 ? $this->_getConfig('countdown_number') : 0;
?>

<script type="text/x-magento-init">
{
	"#maincontent": {
		"BzoTech_AjaxCart/js/ajaxcart-addtocart": {
			"isEnabled": <?php echo $this->_getConfig('isenabled', 1) ? 'true' : 'false'; ?>,
			"isAjaxCart": <?php echo $this->_isAjaxCart() ? 'true' : 'false'; ?>,
			"urlLogin": "<?php echo $this->_urlLogin(); ?>",
			"isLoggedIn": <?php echo $this->_isLoggedIn() ? 'true' : 'false'; ?>,
			"addUrl": "<?php echo $this->getUrl() ?>ajaxcart/cart/add",
			"isUpdateConfigure": <?php echo $this->_isConfigure() ? 'true' : 'false'; ?>,
			"isCompareIndex": <?php echo $this->_isCompareIndex() ? 'true' : 'false'; ?>,
			"isProductView": <?php echo $this->_isProductView() ? 'true' : 'false'; ?>,
			"isCheckoutPage":  <?php echo $this->_isPageCheckout() ? 'true' : 'false'; ?>,
			"isWishlistPage": <?php echo $this->_isWishlistIndex() ? 'true' : 'false'; ?>,
			"urlCurrent": "<?php echo $this->getUrl('*/*/*', ['_current' => true, '_use_rewrite' => true]); ?>",
			"countDownNumber": <?php echo $countdown_number; ?>
		}
	}
}
</script>

<div id="bzo-ajaxcart-container" style="display:none;">
    <div data-role="loader" class="loading-mask">
        <div class="loader">
            <img src="<?php /* @escapeNotVerified */
            echo $block->getViewFileUrl('images/loader-1.gif'); ?>"
                 alt="<?php /* @escapeNotVerified */
                 echo __('Loading...') ?>" width="64" height="64">
        </div>
    </div>
    <div id="bzo-ajaxcart-contents">
    </div>
    <div id="bzo-ajaxcart-report" style="display:none;">
        <div class="bzo-ajaxcart-messages">
        </div>
        <div class="bzo-ajaxcart-actions">
            <a class="action primary bzo-ajaxcart-continue <?php echo $countdown_number ? 'spajaxcart-count' : '' ?>"
               data-count="<?php echo $countdown_number; ?>" href="#" title="<?php echo __('Continue'); ?>">
                <?php echo __('Continue'); ?>
            </a>
            <a class="action primary bzo-ajaxcart-btn bzo-ajaxcart-view-cart " href="<?php echo $this->getUrl('checkout/cart/'); ?>"
               title="<?php echo __('View Cart'); ?>">
                <?php echo __('View Cart'); ?>
            </a>
            <a class="action primary bzo-ajaxcart-btn bzo-ajaxcart-view-compare "
               href="<?php echo $this->getUrl('catalog/product_compare/index/'); ?>"
               title="<?php echo __('Compare Products'); ?>">
                <?php echo __('Compare Products'); ?>
            </a>
            <a class="action primary bzo-ajaxcart-btn bzo-ajaxcart-view-wishlist " href="<?php echo $this->getUrl('wishlist/'); ?>"
               title="<?php echo __('My Wishlist'); ?>">
                <?php echo __('My Wishlist'); ?>
            </a>
        </div>
    </div>
</div>
