<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

use Magento\Catalog\ViewModel\Product\Listing\PreparePostData;
use Magento\Framework\App\ActionInterface;

/* @var $block \Magento\Catalog\Block\Product\AbstractProduct */
/** @var \Magento\Framework\View\Helper\SecureHtmlRenderer $secureRenderer */
$_coreConfig = $this->helper('BzoTech\ThemeCore\Helper\Data');
$_helper     = $block->getData('outputHelper');
?>

<?php
switch ($type = $block->getType()) {
    case 'related-rule':
        if ($exist = $block->hasItems()) {
            $type              = 'related';
            $class             = $type;
            $image             = 'related_products_list';
            $title             = __('Related Products');
            $items             = $block->getAllItems();
            $limit             = $block->getPositionLimit();
            $shuffle           = (int)$block->isShuffled();
            $isWeightedRandom  = (int)$block->getRotation()->isWeightedRandom($block->getProductListType());
            $canItemsAddToCart = $block->canItemsAddToCart();
            $showAddTo         = true;
            $showCart          = false;
            $templateType      = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
            $description       = false;
        }
        break;

    case 'related':
        /** @var \Magento\Catalog\Block\Product\ProductList\Related $block */
        if ($exist = $block->getItems()->getSize()) {
            $type              = 'related';
            $class             = $type;
            $image             = 'related_products_list';
            $title             = __('Related Products');
            $items             = $block->getItems();
            $limit             = 0;
            $shuffle           = 0;
            $isWeightedRandom  = 0;
            $canItemsAddToCart = $block->canItemsAddToCart();
            $showAddTo         = true;
            $showCart          = false;
            $templateType      = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
            $description       = false;
        }
        break;

    default:
        $exist = null;
}
$_item = null;
?>

<?php if ($exist): ?>
    <div class="block block-related product-item-shadow related nav-1 hover-show-nav">
        <div class="block-title title-center">
            <strong class="google-element-font"><?= $block->escapeHtml($title) ?></strong>
        </div>
        <div class="block-content content">
            <div class="products-grid products-<?= $block->escapeHtmlAttr($type) ?>">
                <div class="list items product-items owl-carousel owl-theme">
                    <?php foreach ($items as $_item): ?>
                        <?php $available = ''; ?>
                        <div class="item product product-item <?php echo $_item->getTypeId() ?>">
                            <div class="product-item-info <?= /* @noEscape */
                            $available ?>">
                                <div class="product-image">
                                    <?= /* @noEscape */
                                    '<!-- ' . $image . '-->' ?>
                                    <a href="<?= $block->escapeUrl($block->getProductUrl($_item)) ?>"
                                       class="product photo product-item-photo">
                                        <?= $block->getImage($_item, $image)->toHtml() ?>
                                    </a>

                                    <?= $_coreConfig->getLabelProduct($_item); ?>

                                    <div class="product-item-actions">
                                        <div class="secondary-addto-links actions-secondary"
                                             data-role="add-to-links">
                                            <?php if ($addToBlock = $block->getChildBlock('addto')): ?>
                                                <?= $addToBlock->setProduct($_item)->getChildHtml() ?>
                                            <?php endif; ?>
                                        </div>
                                    </div>
                                </div>
                                <div class="product details product-item-details">
                                    <strong class="product name product-item-name"><a
                                                class="product-item-link"
                                                title="<?= $block->escapeHtmlAttr($_item->getName()) ?>"
                                                href="<?= $block->escapeUrl($block->getProductUrl($_item)) ?>">
                                            <?= $block->escapeHtml($_item->getName()) ?></a>
                                    </strong>

                                    <?php if ($templateType): ?>
                                        <?= $block->getReviewsSummaryHtml($_item, $templateType) ?>
                                    <?php endif; ?>

                                    <?= /* @noEscape */
                                    $block->getProductPrice($_item) ?>

                                    <?php // phpcs:disable ?>
                                    <div class="product-item-inner">
                                        <div class="product actions product-item-actions">
                                            <div class="actions-primary">
                                                <?php if ($_item->isSaleable()): ?>
                                                    <?php if (!$_item->getTypeInstance()->isPossibleBuyFromList($_item)): ?>
                                                        <button
                                                                class="action tocart primary"
                                                                data-mage-init='{"redirectUrl": {"url": "<?= $block->escapeUrl($block->getAddToCartUrl($_item)) ?>"}}'
                                                                type="button"
                                                                title="<?= $block->escapeHtmlAttr(__('Add to Cart')) ?>">
                                                            <span><?= $block->escapeHtml(__('Add to Cart')) ?></span>
                                                        </button>
                                                    <?php else : ?>
                                                        <?php
                                                        /** @var $viewModel PreparePostData */
                                                        $viewModel = $block->getViewModel();
                                                        $postArray = $viewModel->getPostData(
                                                            $block->escapeUrl($block->getAddToCartUrl($_item)),
                                                            ['product' => $_item->getEntityId()]
                                                        );
                                                        $value     = $postArray['data'][ActionInterface::PARAM_NAME_URL_ENCODED];
                                                        ?>
                                                        <form data-role="tocart-form"
                                                              data-product-sku="<?= $block->escapeHtmlAttr($_item->getSku()) ?>"
                                                              action="<?= $block->escapeUrl($block->getAddToCartUrl($_item)) ?>"
                                                              method="post">
                                                            <input type="hidden" name="product"
                                                                   value="<?= /* @noEscape */
                                                                   (int)$_item->getEntityId() ?>">
                                                            <input type="hidden"
                                                                   name="<?= /* @noEscape */
                                                                   ActionInterface::PARAM_NAME_URL_ENCODED ?>"
                                                                   value="<?= /* @noEscape */
                                                                   $value ?>">
                                                            <?= $block->getBlockHtml('formkey') ?>
                                                            <button type="submit"
                                                                    title="<?= $block->escapeHtmlAttr(__('Add to Cart')) ?>"
                                                                    class="action tocart primary">
                                                                <span><?= $block->escapeHtml(__('Add to Cart')) ?></span>
                                                            </button>
                                                        </form>
                                                    <?php endif; ?>
                                                <?php else: ?>
                                                    <?php if ($_item->isAvailable()): ?>
                                                        <div class="stock available">
                                                            <span><?= $block->escapeHtml(__('In stock')) ?></span>
                                                        </div>
                                                    <?php else: ?>
                                                        <div class="stock unavailable">
                                                            <span><?= $block->escapeHtml(__('Out of stock')) ?></span>
                                                        </div>
                                                    <?php endif; ?>
                                                <?php endif; ?>
                                            </div>
                                        </div>
                                    </div>
                                    <?php // phpcs:enable ?>
                                </div>
                            </div>
                        </div>
                    <?php endforeach ?>
                </div>
            </div>
        </div>
    </div>
    <?php if (!$block->isRedirectToCartEnabled() && $_item): ?>
        <script type="text/x-magento-init">
            {
                "[data-role=tocart-form], .form.map.checkout": {
                    "catalogAddToCart": {
                        "product_sku": "<?= $block->escapeJs($_item->getSku()) ?>"
                    }
                }
            }
        </script>
    <?php endif; ?>

    <script>
        require([
            'jquery',
            'bzo_owlCarousel',
            'domReady!'
        ], function ($) {
            $('.block-related .owl-carousel').owlCarousel({
                autoplay: <?php echo $_coreConfig->getSliderConfig('product_detail/related_upsell_group/autoplay'); ?>,
                loop: <?php echo $_coreConfig->getSliderConfig('product_detail/related_upsell_group/loop'); ?>,
                nav: <?php echo $_coreConfig->getSliderConfig('product_detail/related_upsell_group/nav'); ?>,
                navElement: 'div',
                dots: <?php echo $_coreConfig->getSliderConfig('product_detail/related_upsell_group/dots'); ?>,
                margin: <?php echo $_coreConfig->getCoreConfig('product_detail/related_upsell_group/margin'); ?>,
                mouseDrag: <?php echo $_coreConfig->getSliderConfig('product_detail/related_upsell_group/mousedrag'); ?>,
                touchDrag: <?php echo $_coreConfig->getSliderConfig('product_detail/related_upsell_group/touchdrag'); ?>,
                responsive: {
                    0: {
                        items: <?php echo $_coreConfig->getCoreConfig('product_detail/related_upsell_group/screen_0'); ?>,
                    },
                    481: {
                        items: <?php echo $_coreConfig->getCoreConfig('product_detail/related_upsell_group/screen_1'); ?>,
                    },
                    768: {
                        items: <?php echo $_coreConfig->getCoreConfig('product_detail/related_upsell_group/screen_2'); ?>,
                    },
                    992: {
                        items: <?php echo $_coreConfig->getCoreConfig('product_detail/related_upsell_group/screen_3'); ?>,
                    },
                    1200: {
                        items: <?php echo $_coreConfig->getCoreConfig('product_detail/related_upsell_group/screen_4'); ?>,
                    },
                    1441: {
                        items: <?php echo $_coreConfig->getCoreConfig('product_detail/related_upsell_group/screen_5'); ?>,
                    },
                    1681: {
                        items: <?php echo $_coreConfig->getCoreConfig('product_detail/related_upsell_group/screen_6'); ?>,
                    },
                    1921: {
                        items: <?php echo $_coreConfig->getCoreConfig('product_detail/related_upsell_group/screen_7'); ?>,
                    }
                }
            })
        });
    </script>
<?php endif; ?>
