<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

use Magento\Framework\App\Action\Action;

?>
<?php
/**
 * Product list template
 *
 * @var $block \Magento\Catalog\Block\Product\ListProduct
 * @var \Magento\Framework\Escaper $escaper
 * @var \Magento\Framework\View\Helper\SecureHtmlRenderer $secureRenderer
 */
?>
<?php
$_productCollection = $block->getLoadedProductCollection();
/** @var \Magento\Catalog\Helper\Output $_helper */
$_helper           = $block->getData('outputHelper');
$_ajaxSearchConfig = $this->helper('BzoTech\AjaxSearch\Helper\Data');
$limit             = $_ajaxSearchConfig->getAjaxSearchConfig('general/product_limit');
$helperSearch      = $this->helper('Magento\Search\Helper\Data');
$searchKeyword     = $helperSearch->getEscapedQueryText();
?>
<?php
$imageDisplayArea = 'category_page_grid';
$templateType     = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
/**
 * Position for actions regarding image size changing in vde if needed
 */
$pos            = $block->getPositioned();
$additionalHtml = $block->getChildHtml('term-search');
?>

<?php if (strlen($additionalHtml) <= 3 && !$_productCollection->count()) { ?>
    <div class="no-result"><?php echo __('Your search returned no results.') ?></div>
<?php } else { ?>
    <?php if ($additionalHtml && strlen($additionalHtml) > 3) { ?>
        <div class="search-keyword-list">
            <div class="search-keyword">
                <?= $additionalHtml ?>
            </div>
        </div>
    <?php } else { ?>
        <div class="search-keyword-list">
            <div class="search-keyword">
                <dl class="block">
                    <dt class="title"><?php echo __("Related Search Terms") ?></dt>
                </dl>
            </div>
        </div>
    <?php } ?>

    <div class="products-ajax-search">
        <div class="products-ajax-search-list">
            <div class="search-title">
                <span><?php echo __('Product Matches') ?></span>
                <a class="all-result-ajax"
                   href="<?= $this->getBaseUrl() . 'catalogsearch/result/?q=' . $searchKeyword ?>"><?php echo __('All results') ?>
                    <span class="count">(<?php echo $_productCollection->count() ?>)</span>
                </a>
            </div>

            <ol class="product-items">
                <?php /** @var $_product \Magento\Catalog\Model\Product */ ?>
                <?php $i = 0;
                foreach ($_productCollection as $_product): $i++; ?>
                    <li class="item product product-item">
                        <div class="product-item-info">
                            <?php
                            $productImage = $block->getImage($_product, $imageDisplayArea);
                            if ($pos != null) {
                                $position = 'left:' . $productImage->getWidth() . 'px;'
                                    . 'top:' . $productImage->getHeight() . 'px;';
                            }
                            ?>
                            <?php // Product Image ?>
                            <a href="<?= $escaper->escapeUrl($_product->getProductUrl()) ?>"
                               class="product photo product-item-photo"
                               tabindex="-1">
                                <?= $productImage->toHtml() ?>
                            </a>
                            <div class="product details product-item-details">
                                <?php $_productNameStripped = $block->stripTags($_product->getName(), null, true); ?>
                                <strong class="product name product-item-name">
                                    <a class="product-item-link"
                                       href="<?= $escaper->escapeUrl($_product->getProductUrl()) ?>">
                                        <?= /* @noEscape */
                                        $_helper->productAttribute($_product, $_product->getName(), 'name') ?>
                                    </a>
                                </strong>
                                <?= $block->getReviewsSummaryHtml($_product, $templateType) ?>

                                <?php echo $block->getProductPrice($_product); ?>
                            </div>
                        </div>
                    </li>

                    <?php if ($i == $limit) {
                        break;
                    } ?>
                <?php endforeach; ?>
            </ol>
        </div>
    </div>
<?php } ?>
