<?php
/**
 * @category BZOTech
 * @package BzoTech_AjaxLayeredNavigation
 * @version 1.0.0
 * @copyright Copyright (c) 2022 BZOTech Company. All Rights Reserved.
 * @license - Copyrighted Commercial Software
 * @author BZOTech Company <contact@bzotech.com>
 * @link https://bzotech.com
 */
?>

<div data-role="loader" class="loading-mask-ajaxlayerednavigation" style="display:none">
    <div class="loader">
        <img src="<?php /* @escapeNotVerified */
        echo $block->getViewFileUrl('images/loader-1.gif'); ?>"
             alt="<?php /* @escapeNotVerified */
             echo __('Loading...') ?>" width="64" height="64">
    </div>
</div>  