<?php
/**
 * @category BZOTech
 * @package BzoTech_ProductTabs
 * @version 1.0.0
 * @copyright Copyright (c) 2022 BZOTech Company. All Rights Reserved.
 * @license - Copyrighted Commercial Software
 * @author BZOTech Company <contact@bzotech.com>
 * @link https://bzotech.com
 */

$list = $this->getData('list');
?>
<div class="list-tabs">
    <div class="tabs-drop-mobile"></div>
    <div class="list-product-tabs">
        <?php
        foreach ($list as $tab) {
            ?>
            <div class="item-tab <?php echo isset($tab['sel']) ? '  active loaded' : ''; ?>  "
                data-tabid="<?php echo $tab['id_tab']; ?>" data-catids="<?php echo $tab['cat_children'] ?>">
				<span
                        class="item-tab-label">
						<?php echo $tab['name_tab']; ?>
				</span>
            </div>
            <?php
        } ?>
    </div>
</div>
