.breadcrumbs-title .breadcrumbs strong{
color: #<?php echo $themeColor; ?>;
}

.breadcrumbs-title .breadcrumbs a:hover{
color: #<?php echo $themeColor; ?>;
}

.page-layout-1column .filter-options .filter-options-content .item a:hover{
color: #<?php echo $themeColor; ?>;
}

.page-layout-1column .filter-options .filter-options-content .item a:hover:before,
.sidebar .block.filter .items .my.item a:hover:before{
border-color: #<?php echo $themeColor; ?>;
}

.page-layout-2columns-left #narrow-by-list .filter-options-title.filter-options-title:before,
.page-layout-2columns-right #narrow-by-list .filter-options-title.filter-options-title:before{
background-color: #<?php echo $themeColor; ?>;
}

.page-layout-2columns-left #narrow-by-list .filter-options-content .item a:hover,
.page-layout-2columns-right #narrow-by-list .filter-options-content .item a:hover{
color: #<?php echo $linkHoverColor; ?>;
}

#price-slider .ui-slider-range{
background-color: #<?php echo $themeColor; ?>;
}

#price-slider .ui-slider-handle:before{
border: 4px solid #<?php echo $themeColor; ?>;
}

.filter-actions a{
background-color: #<?php echo $themeColor; ?>;
color: #<?php echo $textOnThemeColor; ?>;
}

.page-layout-2columns-left .filter-actions a:hover,
.page-layout-2columns-right .filter-actions a:hover{
background-color: #<?php echo $themeColorDarken; ?>;
}

.pages .pages-items li a:hover,
.pages .pages-items li strong{
background-color: #<?php echo $themeColor; ?>;
border-color: #<?php echo $themeColor; ?>;
color: #<?php echo $textOnThemeColor; ?>;
}

.autoparts-theme .breadcrumbs strong{
color: #<?php echo $themeColor; ?>;
}

.motobike-theme .breadcrumbs a:hover{
color: #<?php echo $linkHoverColor; ?>;
}