.product.media .product-addto-links .action:hover{
background-color: #<?php echo $themeColor; ?>;
border-color: #<?php echo $themeColor; ?>;
}

.sidebar-livechat .live-chat-link a{
color: #<?php echo $themeColor; ?>;
}

.sidebar .bzotech-slider-product.bzotech-slider-list .owl-theme .owl-dots .owl-dot:hover span,
.sidebar .bzotech-slider-product.bzotech-slider-list .owl-theme .owl-dots .owl-dot.active span{
background-color: #<?php echo $themeColor; ?>;
}

.detail-info-container .product-info-main .product-reviews-summary .reviews-actions a:hover{
color: #<?php echo $linkHoverColor; ?>;
}

.bundle-options-container .block-bundle-summary .box-tocart .actions .tocart{
background-color: #<?php echo $themeColor; ?>;
color: #<?php echo $textOnThemeColor; ?>;
}

.bundle-options-container .block-bundle-summary .box-tocart .actions .tocart:hover{
background-color: #<?php echo $themeColorDarken; ?>;
}

.product-info-main .box-tocart .actions button.tocart:hover{
background-color: #<?php echo $themeColorDarken; ?>;
}

.page-product-downloadable .product-add-form .product-options-bottom .box-tocart .actions .tocart{
background-color: #<?php echo $themeColor; ?>;
color: #<?php echo $textOnThemeColor; ?>;
}

.page-product-downloadable .product-add-form .product-options-bottom .box-tocart .actions .tocart:hover{
background-color: #<?php echo $themeColorDarken; ?>;
}

.page-product-downloadable .product-add-form .product-options-bottom .box-tocart .actions .buynow,
.detail-info-container .product-info-main .box-tocart .actions button.buynow,
.bundle-options-container .block-bundle-summary .box-tocart .actions .buynow {
background-color: #<?php echo $themeColor; ?>;
color: #<?php echo $textOnThemeColor; ?>;
}

.page-product-downloadable .product-add-form .product-options-bottom .box-tocart .actions .buynow:hover,
.detail-info-container .product-info-main .box-tocart .actions button.buynow:hover,
.bundle-options-container .block-bundle-summary .box-tocart .actions .buynow:hover {
background-color: #<?php echo $themeColorDarken; ?>;
}

.default-style .resp-tabs-list li:hover,
.default-style .resp-tabs-list li.active{
color: #<?php echo $themeColor; ?>;
}