/**
* Footer 1
*/

.footer-style-1 .text-email a{
color: #<?php echo $themeColor; ?>;
}

.footer-style-1 .call-order .call-phone a{
color: #<?php echo $themeColor; ?>;
}

.footer-style-1 .block-subscribe-footer .action-button button{
background-color: #<?php echo $themeColor; ?>;
}

.footer-style-1 .block-subscribe-footer .action-button button:hover{
background-color: #<?php echo $themeColorDarken; ?>;
}