/**
* Header General
*/
.bzo-popup-modal .actions-toolbar .primary button{
background-color: #<?php echo $themeColor; ?>;
color: #<?php echo $textOnThemeColor; ?>;
}

.megamenu-nav a:hover:hover{
color: #<?php echo $linkHoverColor; ?>;
}

.column-featured .featured-items li a:hover{
color: #<?php echo $linkHoverColor; ?>;
}

/**
* Header 1
*/
.header-1-style .header-desktop .hd-top-support ul li a:hover,
.header-1-style .header-services > ul > li > a:hover{
color: #<?php echo $themeColor; ?>;
}

.header-1-style .header-services .dropdown-block:hover > a{
color: #<?php echo $themeColor; ?>;
}

.header-1-style .header-bottom .megamenu-nav.horizontal-type .megamenu-items > li:hover > a,
.header-1-style .header-bottom .megamenu-nav.horizontal-type .megamenu-items > li.active > a,
.header-1-style .header-bottom .megamenu-nav.horizontal-type .megamenu-items > li.has-active > a{
color: #<?php echo $themeColor; ?>;
}

.header-1-style .header-bottom .megamenu-nav.horizontal-type .megamenu-items > li > a:before{
background-color: #<?php echo $themeColor; ?>;
}

.header-1-style .hd-cart .minicart-wrapper .action.showcart .counter,
.header-1-style .header-wishlist .count{
background-color: #<?php echo $themeColor; ?>;
color: #<?php echo $textOnThemeColor; ?>;
}

.header-1-style .header-services .hd-top-services > li > a:hover{
color: #<?php echo $linkHoverColor; ?>;
}

.megamenu-nav .megamenu-items > li > .dropdowm-megamenu.type-megamenu > .middle-level-0 > .megamenu-content-cate > .submenu > li > a{
color: #<?php echo $linkColor; ?>;
}