.block-tab-home .block-title a,
.block-product-list .block-title a,
.block-home-services .block-title a,
.block-home-choose .block-title a,
.block-home-partner .block-title a{
border: 1px solid #<?php echo $themeColor; ?>;
background-color: #<?php echo $themeColor; ?>;
color: #<?php echo $textOnThemeColor; ?>;
}

.block-tab-home .block-title a:hover,
.block-product-list .block-title a:hover,
.block-home-services .block-title a:hover,
.block-home-choose .block-title a:hover,
.block-home-partner .block-title a:hover{
border: 1px solid #<?php echo $themeColorDarken; ?>;
background-color: #<?php echo $themeColorDarken; ?>;
color: #<?php echo $textOnThemeColor; ?>;
}

.block-home-partner ul li a:hover{
border-color: #<?php echo $themeColor; ?>;
}

.block-home-services .item .read-more a{
color: #<?php echo $themeColor; ?>;
}

.block-home-services .item:hover{
border-color: #<?php echo $themeColor; ?>;
}

.block-cate-home .category-item .parent-name a{
color: #<?php echo $linkColor; ?>;
}

.block-cate-home .category-item .parent-name a:hover{
color: #<?php echo $linkHoverColor; ?>;
}

.nav-1 .owl-theme .owl-nav [class*=owl-]:hover{
background-color: #<?php echo $themeColor; ?>;
color: #<?php echo $textOnThemeColor; ?>;
}

.block-product-list .product-item-actions .actions-primary .tocart:hover{
background-color: #<?php echo $themeColor; ?>;
}

.block-product-list .bzotech-slider-list .product-item-info .product-item-name a{
color: #<?php echo $linkColor; ?>;
}

.block-product-list .bzotech-slider-list .product-item-info .product-item-name a:hover{
color: #<?php echo $linkHoverColor; ?>;
}

.block-post-home .categories a, .block-post-home .read-more a{
color: #<?php echo $themeColor; ?>;
}

.block-product-list .product-item-info:hover{
border-color: #<?php echo $themeColor; ?>;
}

@media (min-width: 768px) {
.block-tab-home .list-product-tabs .item-tab:hover,
.block-tab-home .list-product-tabs .item-tab.active{
background-color: #<?php echo $themeColor; ?>;
border-color: #<?php echo $themeColor; ?>;
color: #<?php echo $textOnThemeColor; ?>;
}

.block-tab-home .list-product-tabs .item-tab:before{
background-color: #<?php echo $textOnThemeColor; ?>;
}
}

