/**
* 404 Not Found
*/

.notfound-container .notfound-action a.go-back{
background-color: #<?php echo $themeColor; ?>;
color: #<?php echo $textOnThemeColor; ?>;
}

.notfound-container .notfound-action a.go-home:hover{
background-color: #<?php echo $themeColor; ?>;
color: #<?php echo $textOnThemeColor; ?>;
}

/*
* Blog
*/

.widget.block-archive ul li .archive-item-link:hover,
.widget.block-categories ul li a:hover{
color: #<?php echo $linkHoverColor; ?>;
}

.widget.blog-tags ul li a:hover{
background-color: #<?php echo $themeColor; ?>;
color: #<?php echo $textOnThemeColor; ?>;
}

.post-list.modern .post-read-more a.post-read:hover{
background-color: #<?php echo $themeColor; ?>;
border-color: #<?php echo $themeColor; ?>;
color: #<?php echo $textOnThemeColor; ?>;
}

.post-list.modern .post-image .post-category a{
background-color: #<?php echo $themeColor; ?>;
color: #<?php echo $textOnThemeColor; ?>;
}

.post-list.modern .post-image .post-category a:hover{
background-color: #<?php echo $themeColorDarken; ?>;
}

.c-replyform button{
background-color: #<?php echo $themeColor; ?>;
color: #<?php echo $textOnThemeColor; ?>;
}

/**
* Contact
*/

.contact-block .primary button{
background-color: #<?php echo $themeColor; ?>;
color: #<?php echo $textOnThemeColor; ?>;
}

.contact-block .primary button:hover{
background-color: #<?php echo $themeColorDarken; ?>;
}

.contact-content .contact-col-info .contact-detail li.time span{
color: #<?php echo $themeColor; ?>;
}

/**
* Partner
*/

.brand-partner ul li a:hover{
border-color: #<?php echo $themeColor; ?>;
}

.partner-brand .item-inner:hover{
border-color: #<?php echo $themeColor; ?>;
}

/**
* Popup Newsletter
*/

.newsletter-popup-container .block.newsletter .actions button{
background-color: #<?php echo $themeColor; ?>;
color: #<?php echo $textOnThemeColor; ?>;
}

.newsletter-popup-container .block.newsletter .actions button:hover{
background-color: #<?php echo $themeColorDarken; ?>;
}

/**
* Shopping cart
*/

.cart-container .checkout-methods-items .action.primary{
background-color: #<?php echo $themeColor; ?>;
color: #<?php echo $textOnThemeColor; ?>;
}

.cart-container .checkout-methods-items .action.primary:hover{
background-color: #<?php echo $themeColorDarken; ?>;
}

/**
* Tabs page
*/

.page-tab-product .loadmore-container .loadmore-button{
background-color: #<?php echo $themeColor; ?>;
color: #<?php echo $textOnThemeColor; ?>;
}

@media (min-width: 768px) {
.page-tab-product .list-product-tabs .item-tab:hover,
.page-tab-product .list-product-tabs .item-tab.active{
background-color: #<?php echo $themeColor; ?>;
border-color: #<?php echo $themeColor; ?>;
color: #<?php echo $textOnThemeColor; ?>;
}
}
