/**
* Product 1
*/

.product-1-style .products-grid .product-item-actions .actions-secondary .action:hover{
background-color: #<?php echo $themeColor; ?>;
}

.product-1-style .products-grid .product-item-name a:hover{
color: #<?php echo $linkHoverColor; ?>;
}

.product-1-style .products-grid .product-item-info:hover .product-item-actions .actions-primary .tocart{
background-color: #<?php echo $themeColor; ?>;
}

.product-1-style .products-grid .product-item-info .product-item-actions .actions-primary .tocart:hover{
background-color: #<?php echo $themeColorDarken; ?>;
}

.product-1-style .products-list .product-item-info .actions-primary .tocart:hover{
background-color: #<?php echo $themeColor; ?>;
color: #<?php echo $textOnThemeColor; ?>;
}

.product-1-style .products-list .product-item-info .product-item-name a:hover{
color: #<?php echo $themeColor; ?>;
}

.product-1-style .products-list .product-item-info .actions-secondary .action:hover,
.product-1-style .products-list .product-item-info .product-reviews-summary .reviews-actions a:hover{
color: #<?php echo $themeColor; ?>;
}