<?php
/**
 * Copyright © Magefan (support@magefan.com). All rights reserved.
 * Please visit Magefan.com for license details (https://magefan.com/end-user-license-agreement).
 *
 * Glory to Ukraine! Glory to the heroes!
 */
?>
<?php
/**
 * Blog post next and prev post links
 *
 * @var $block \Magefan\Blog\Block\Post\View\NextPrev
 */
?>

<?php if ($block->displayLinks()) { ?>
    <?php
    $prevPost = $block->getPrevPost();
    $nextPost = $block->getNextPost();
    ?>
    <?php if ($prevPost || $nextPost) { ?>
        <div class="post-nextprev-hld clearfix">
            <?php if ($prevPost) { ?>
                <div class="prev-post">
                    <?php $title = $block->escapeHtml($prevPost->getTitle()) ?>
                    <a class="link-prev"
                       href="<?= $block->escapeUrl($prevPost->getPostUrl()) ?>"
                       title="<?= $block->escapeHtml(__('Read %1', $title)) ?>">
                        <?= $block->escapeHtml(__('Previous')) ?>
                    </a>

                    <div class="link-post">
                        <a href="<?= $block->escapeUrl($prevPost->getPostUrl()) ?>"
                           title="<?= $block->escapeHtml(__('Read %1', $title)) ?>">
                            <?= $block->escapeHtml(__($title)) ?>
                        </a>
                    </div>
                </div>
            <?php } ?>
            <?php if ($nextPost) { ?>
                <div class="next-post">
                    <?php $title = $block->escapeHtml($nextPost->getTitle()) ?>
                    <a class="link-next"
                       href="<?= $block->escapeUrl($nextPost->getPostUrl()) ?>"
                       title="<?= $block->escapeHtml(__('Read %1', $title)) ?>">
                        <?= $block->escapeHtml(__('Next')) ?>
                    </a>

                    <div class="link-post">
                        <a href="<?= $block->escapeUrl($nextPost->getPostUrl()) ?>"
                           title="<?= $block->escapeHtml(__('Read %1', $title)) ?>">
                            <?= $block->escapeHtml(__($title)) ?>
                        </a>
                    </div>
                </div>
            <?php } ?>
        </div>
    <?php } ?>
<?php } ?>
