<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/**
 * @var \Magento\Search\Block\Term $block
 * @var \Magento\Framework\View\Helper\SecureHtmlRenderer $secureRenderer
 */
?>
<?php if (count($block->getTerms()) > 0): ?>
    <ul class="search-terms-header">
        <li class="term-label"><?php echo __('Trending Now:') ?></li>
        <?php foreach ($block->getTerms() as $_term): ?>
            <li class="item-term">
                <a href="<?= $block->escapeUrl($block->getSearchUrl($_term)) ?>">
                    <?= $block->escapeHtml($_term->getQueryText()) ?>
                </a>
            </li>
        <?php endforeach; ?>
    </ul>
<?php endif; ?>
